export const environment = {
  NEXT_PUBLIC_APIURL: process.env.NEXT_PUBLIC_APIURL,
  NEXT_PUBLIC_BRANDNAME: process.env.NEXT_PUBLIC_BRANDNAME,
  NEXT_PUBLIC_HOMEURL: process.env.NEXT_PUBLIC_HOMEURL,
  NEXT_PUBLIC_PUBLICURL: process.env.NEXT_PUBLIC_PUBLICURL,
  NEXT_PUBLIC_FEEDBACKURL: process.env.NEXT_PUBLIC_FEEDBACKURL,
  NEXT_PUBLIC_CONTACTEMAIL: process.env.NEXT_PUBLIC_CONTACTEMAIL,
  NEXT_PUBLIC_CONTACTNUMBER: process.env.NEXT_PUBLIC_CONTACTNUMBER,
  NEXT_PUBLIC_META_DESCRIPTION: process.env.NEXT_PUBLIC_META_DESCRIPTION,
  NEXT_PUBLIC_SEARCH_TITLE: process.env.NEXT_PUBLIC_SEARCH_TITLE,
  NEXT_PUBLIC_SEARCH_LABEL: process.env.NEXT_PUBLIC_SEARCH_LABEL,
  NEXT_PUBLIC_SEARCH_SUBTITLE: process.env.NEXT_PUBLIC_SEARCH_SUBTITLE,
  NEXT_PUBLIC_SEARCH_SUBTITLEURLTEXT:
    process.env.NEXT_PUBLIC_SEARCH_SUBTITLEURLTEXT,
  NEXT_PUBLIC_SEARCH_SUBTITLEURL: process.env.NEXT_PUBLIC_SEARCH_SUBTITLEURL,
  NEXT_PUBLIC_ALERTSEARCH_TEXT: process.env.NEXT_PUBLIC_ALERTSEARCH_TEXT,
  NEXT_PUBLIC_ALERTSEARCH_BUTTONTEXT:
    process.env.NEXT_PUBLIC_ALERTSEARCH_BUTTONTEXT,
  NEXT_PUBLIC_ALERTSEARCH_URL: process.env.NEXT_PUBLIC_ALERTSEARCH_URL,
  NEXT_PUBLIC_SERVICES_AUTH_COGNITO_REGION:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_REGION,
  NEXT_PUBLIC_SERVICES_AUTH_COGNITO_USERPOOLID:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_USERPOOLID,
  NEXT_PUBLIC_SERVICES_AUTH_COGNITO_CLIENTID:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_CLIENTID,
  NEXT_PUBLIC_SERVICES_MAP_GOOGLE_APIKEY:
    process.env.NEXT_PUBLIC_SERVICES_MAP_GOOGLE_APIKEY,
  NEXT_PUBLIC_SERVICES_MAP_CENTER_LAT:
    process.env.NEXT_PUBLIC_SERVICES_MAP_CENTER_LAT,
  NEXT_PUBLIC_SERVICES_MAP_CENTER_LON:
    process.env.NEXT_PUBLIC_SERVICES_MAP_CENTER_LON,
  NEXT_PUBLIC_SERVICES_PLACES_GOOGLE_APIKEY:
    process.env.NEXT_PUBLIC_SERVICES_PLACES_GOOGLE_APIKEY,
  NEXT_PUBLIC_THEME_BASEFONTSIZE: process.env.NEXT_PUBLIC_THEME_BASEFONTSIZE,
  NEXT_PUBLIC_THEME_PRIMARYCOLOR: process.env.NEXT_PUBLIC_THEME_PRIMARYCOLOR,
  NEXT_PUBLIC_THEME_PRIMARYMEDIUMCOLOR:
    process.env.NEXT_PUBLIC_THEME_PRIMARYMEDIUMCOLOR,
  NEXT_PUBLIC_THEME_PRIMARYLIGHTCOLOR:
    process.env.NEXT_PUBLIC_THEME_PRIMARYLIGHTCOLOR,
  NEXT_PUBLIC_THEME_SECONDARYCOLOR:
    process.env.NEXT_PUBLIC_THEME_SECONDARYCOLOR,
  NEXT_PUBLIC_THEME_SECONDARYMEDIUMCOLOR:
    process.env.NEXT_PUBLIC_THEME_SECONDARYMEDIUMCOLOR,
  NEXT_PUBLIC_THEME_SECONDARYLIGHTCOLOR:
    process.env.NEXT_PUBLIC_THEME_SECONDARYLIGHTCOLOR,
  NEXT_PUBLIC_THEME_ERRORCOLOR: process.env.NEXT_PUBLIC_THEME_ERRORCOLOR,
  NEXT_PUBLIC_THEME_SUCCESSCOLOR: process.env.NEXT_PUBLIC_THEME_SUCCESSCOLOR,
  NEXT_PUBLIC_THEME_BORDERRADIUS: process.env.NEXT_PUBLIC_THEME_BORDERRADIUS,
};
