export const environment = {
  APIURL: process.env.NEXT_PUBLIC_APIURL,
  BRANDNAME: process.env.NEXT_PUBLIC_BRANDNAME,
  HOMEURL: process.env.NEXT_PUBLIC_HOMEURL,
  PUBLICURL: process.env.NEXT_PUBLIC_PUBLICURL,
  FEEDBACKURL: process.env.NEXT_PUBLIC_FEEDBACKURL,
  CONTACTEMAIL: process.env.NEXT_PUBLIC_CONTACTEMAIL,
  CONTACTNUMBER: process.env.NEXT_PUBLIC_CONTACTNUMBER,
  META_DESCRIPTION: process.env.NEXT_PUBLIC_META_DESCRIPTION,
  SEARCH_TITLE: process.env.NEXT_PUBLIC_SEARCH_TITLE,
  SEARCH_LABEL: process.env.NEXT_PUBLIC_SEARCH_LABEL,
  SEARCH_SUBTITLE: process.env.NEXT_PUBLIC_SEARCH_SUBTITLE,
  SEARCH_SUBTITLEURLTEXT: process.env.NEXT_PUBLIC_SEARCH_SUBTITLEURLTEXT,
  SEARCH_SUBTITLEURL: process.env.NEXT_PUBLIC_SEARCH_SUBTITLEURL,
  ALERTSEARCH_TEXT: process.env.NEXT_PUBLIC_ALERTSEARCH_TEXT,
  ALERTSEARCH_BUTTONTEXT: process.env.NEXT_PUBLIC_ALERTSEARCH_BUTTONTEXT,
  ALERTSEARCH_URL: process.env.NEXT_PUBLIC_ALERTSEARCH_URL,
  SERVICES_AUTH_COGNITO_REGION:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_REGION,
  SERVICES_AUTH_COGNITO_USERPOOLID:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_USERPOOLID,
  SERVICES_AUTH_COGNITO_CLIENTID:
    process.env.NEXT_PUBLIC_SERVICES_AUTH_COGNITO_CLIENTID,
  SERVICES_MAP_GOOGLE_APIKEY:
    process.env.NEXT_PUBLIC_SERVICES_MAP_GOOGLE_APIKEY,
  SERVICES_MAP_CENTER_LAT: process.env.NEXT_PUBLIC_SERVICES_MAP_CENTER_LAT,
  SERVICES_MAP_CENTER_LON: process.env.NEXT_PUBLIC_SERVICES_MAP_CENTER_LON,
  SERVICES_PLACES_GOOGLE_APIKEY:
    process.env.NEXT_PUBLIC_SERVICES_PLACES_GOOGLE_APIKEY,
  THEME_BASEFONTSIZE: process.env.NEXT_PUBLIC_THEME_BASEFONTSIZE,
  THEME_PRIMARYCOLOR: process.env.NEXT_PUBLIC_THEME_PRIMARYCOLOR,
  THEME_PRIMARYMEDIUMCOLOR: process.env.NEXT_PUBLIC_THEME_PRIMARYMEDIUMCOLOR,
  THEME_PRIMARYLIGHTCOLOR: process.env.NEXT_PUBLIC_THEME_PRIMARYLIGHTCOLOR,
  THEME_SECONDARYCOLOR: process.env.NEXT_PUBLIC_THEME_SECONDARYCOLOR,
  THEME_SECONDARYMEDIUMCOLOR:
    process.env.NEXT_PUBLIC_THEME_SECONDARYMEDIUMCOLOR,
  THEME_SECONDARYLIGHTCOLOR: process.env.NEXT_PUBLIC_THEME_SECONDARYLIGHTCOLOR,
  THEME_ERRORCOLOR: process.env.NEXT_PUBLIC_THEME_ERRORCOLOR,
  THEME_SUCCESSCOLOR: process.env.NEXT_PUBLIC_THEME_SUCCESSCOLOR,
  THEME_BORDERRADIUS: process.env.NEXT_PUBLIC_THEME_BORDERRADIUS,
};
